// Generated by CoffeeScript 1.4.0
(function() {
  var game;

  this.game = function(canvas) {
    console.log(canvas);
    this.canvas = document.getElementById(canvas);
    console.log(this.canvas);
    this.portview=this.canvas.getContext("2d");
    this.width = this.canvas.width;
    this.height = this.canvas.height;
    //this.portview.fillStyle = '#000';
    this.canvas.fillStyle = '#000';
    console.log(this.width + ' ' + this.height);
    this.portview.fillRect(0,0,150,75);
  };
  //console.log(game);

}).call(this);


